#! /bin/bash

if [ "$1" == "-v" ]; then
 echo 1
fi

if [ "$1" == "--version" ]; then
 echo 1
fi

if [ "$1" == "-c" ]; then
 echo -e "• initial release"
fi

if [ "$1" == "--changelog" ]; then
 echo -e "• initial release"
fi


if [ "$1" == "-a" ]; then
 echo -e "This is brought to you by \e[1mAlexandru Balan\e[21m under the"
 echo -e "\e[1mPearProject Team\e[21m"
 echo ""
 echo "Copyright 2021 © PearProject All Rights Reserved"
fi


if [ "$1" == "--authors" ]; then
 echo -e "This is brought to you by \e[1mAlexandru Balan\e[21 munder the"
 echo -e "\e[1mPearProject Team\e[21m"
 echo ""
 echo "Copyright 2021 © PearProject All Rights Reserved"
fi

if [ "$1" == "-p" ]; then
 echo -e "\e[1;4mTrying to send $3 to SourceHub.\e[0m"
 scp -i /path/to/key.pem $2 user@ip:/path/to/destination
fi

if [ "$1" == "--push" ]; then
 echo -e "\e[1;4mTrying to send $3 to SourceHub.\e[0m"
 scp -i /path/to/key.pem $2 user@ip:/path/to/destination
fi

if [ "$1" == "push" ]; then
 echo -e "\e[1;4mTrying to send $3 to SourceHub.\e[0m"
 scp -i /path/to/key.pem $2 user@ip:/path/to/destination
fi

if [ "$1" == "" ]; then
 echo -e "\e[1;4mWelcome to SourceHub repository manager\e[24m"
 echo -e "Usage:  -v  --version      SourceHub CLI version"
 echo -e "        -c  --changelog    Show the changelog"
 echo -e "        -a  --author       Show the author of the pear Updates Manager"
 echo -e "        -m  --commit       Commit changes"
 echo -e "        -h  --help         Display this help screen\e[0m"
fi


if [ "$1" == "-h" ]; then
 echo -e "\e[1;4mWelcome to SourceHub repository manager\e[24m"
 echo -e "Usage:  -v  --version      SourceHub CLI version"
 echo -e "        -c  --changelog    Show the changelog"
 echo -e "        -a  --author       Show the author of the pear Updates Manager"
 echo -e "        -m  --commit       Commit changes"
 echo -e "        -h  --help         Display this help screen\e[0m"
fi

if [ "$1" == "--help" ]; then
 echo -e "\e[1;4mWelcome to SourceHub repository manager\e[24m"
 echo -e "Usage:  -v  --version      SourceHub CLI version"
 echo -e "        -c  --changelog    Show the changelog"
 echo -e "        -a  --author       Show the author of the pear Updates Manager"
 echo -e "        -m  --commit       Commit changes"
 echo -e "        -h  --help         Display this help screen\e[0m"
fi

#if [ "$2" == "" ]; then
#echo "Missing KEY!"
#fi

#if [ "$3" == "" ]; then
#echo "Missing file to upload"
#fi
